const assert = require('assert')
const fs = require('fs')
const os = require('os')
const path = require('path')
const { PearOpsPeer } = require('../src/peer')
const { createKeetIdentity } = require('../src/identity')

;(async () => {
  const storage = fs.mkdtempSync(path.join(os.tmpdir(), 'pearops-state-peer-'))
  const identityStorage = path.join(storage, 'identity')
  await createKeetIdentity(identityStorage)
  const peer = new PearOpsPeer({ name: 'Verifier', storage, identityStorage })
  const snap = await peer.createRoom({ title: 'Verifier incident', severity: 'SEV-2' })
  assert.ok(snap.roomKey.startsWith('pearops:'), 'room key generated')
  await peer.postEvent({ eventType: 'investigation', message: 'Checked checkout API latency' })
  await peer.setStatus('triaging')
  const after = peer.snapshot()
  assert.equal(after.metadata.status, 'triaging')
  assert.equal(after.metadata.state, 'triaging')
  assert.ok(after.identity.identityPublicKey, 'snapshot exposes Keet identity public key')
  assert.ok(after.timeline.every(e => e.identity?.verified), 'timeline events are Keet identity verified')
  assert.ok(after.timeline.some(e => e.eventType === 'investigation'), 'MVP event type is supported')
  await peer.close()
  console.log(JSON.stringify({ ok: true, events: after.timeline.length, status: after.metadata.status, state: after.metadata.state }))
})().catch(err => { console.error(err); process.exit(1) })
